//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesFactura.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calculos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Calculos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseImponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Bruto {
            get {
                return this.BrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.BrutoField, value) != true)) {
                    this.BrutoField = value;
                    this.RaisePropertyChanged("Bruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescuentoField, value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BaseImponible {
            get {
                return this.BaseImponibleField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseImponibleField, value) != true)) {
                    this.BaseImponibleField = value;
                    this.RaisePropertyChanged("BaseImponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Iva {
            get {
                return this.IvaField;
            }
            set {
                if ((object.ReferenceEquals(this.IvaField, value) != true)) {
                    this.IvaField = value;
                    this.RaisePropertyChanged("Iva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Total {
            get {
                return this.TotalField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalField, value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CalculosFacturaWSSoap")]
    public interface CalculosFacturaWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CalculosLineaFacturaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculosLineaFactura", ReplyAction="*")]
        GesFactura.ServiceReference1.CalculosLineaFacturaResponse CalculosLineaFactura(GesFactura.ServiceReference1.CalculosLineaFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculosLineaFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<GesFactura.ServiceReference1.CalculosLineaFacturaResponse> CalculosLineaFacturaAsync(GesFactura.ServiceReference1.CalculosLineaFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        GesFactura.ServiceReference1.HelloWorldResponse HelloWorld(GesFactura.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<GesFactura.ServiceReference1.HelloWorldResponse> HelloWorldAsync(GesFactura.ServiceReference1.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculosLineaFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculosLineaFactura", Namespace="http://tempuri.org/", Order=0)]
        public GesFactura.ServiceReference1.CalculosLineaFacturaRequestBody Body;
        
        public CalculosLineaFacturaRequest() {
        }
        
        public CalculosLineaFacturaRequest(GesFactura.ServiceReference1.CalculosLineaFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculosLineaFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double tipo_descuento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double tipo_iva;
        
        public CalculosLineaFacturaRequestBody() {
        }
        
        public CalculosLineaFacturaRequestBody(double cantidad, double precio, double tipo_descuento, double tipo_iva) {
            this.cantidad = cantidad;
            this.precio = precio;
            this.tipo_descuento = tipo_descuento;
            this.tipo_iva = tipo_iva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculosLineaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculosLineaFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GesFactura.ServiceReference1.CalculosLineaFacturaResponseBody Body;
        
        public CalculosLineaFacturaResponse() {
        }
        
        public CalculosLineaFacturaResponse(GesFactura.ServiceReference1.CalculosLineaFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculosLineaFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GesFactura.ServiceReference1.Calculos CalculosLineaFacturaResult;
        
        public CalculosLineaFacturaResponseBody() {
        }
        
        public CalculosLineaFacturaResponseBody(GesFactura.ServiceReference1.Calculos CalculosLineaFacturaResult) {
            this.CalculosLineaFacturaResult = CalculosLineaFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public GesFactura.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(GesFactura.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public GesFactura.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(GesFactura.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculosFacturaWSSoapChannel : GesFactura.ServiceReference1.CalculosFacturaWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculosFacturaWSSoapClient : System.ServiceModel.ClientBase<GesFactura.ServiceReference1.CalculosFacturaWSSoap>, GesFactura.ServiceReference1.CalculosFacturaWSSoap {
        
        public CalculosFacturaWSSoapClient() {
        }
        
        public CalculosFacturaWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculosFacturaWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculosFacturaWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculosFacturaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GesFactura.ServiceReference1.CalculosLineaFacturaResponse GesFactura.ServiceReference1.CalculosFacturaWSSoap.CalculosLineaFactura(GesFactura.ServiceReference1.CalculosLineaFacturaRequest request) {
            return base.Channel.CalculosLineaFactura(request);
        }
        
        public GesFactura.ServiceReference1.Calculos CalculosLineaFactura(double cantidad, double precio, double tipo_descuento, double tipo_iva) {
            GesFactura.ServiceReference1.CalculosLineaFacturaRequest inValue = new GesFactura.ServiceReference1.CalculosLineaFacturaRequest();
            inValue.Body = new GesFactura.ServiceReference1.CalculosLineaFacturaRequestBody();
            inValue.Body.cantidad = cantidad;
            inValue.Body.precio = precio;
            inValue.Body.tipo_descuento = tipo_descuento;
            inValue.Body.tipo_iva = tipo_iva;
            GesFactura.ServiceReference1.CalculosLineaFacturaResponse retVal = ((GesFactura.ServiceReference1.CalculosFacturaWSSoap)(this)).CalculosLineaFactura(inValue);
            return retVal.Body.CalculosLineaFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GesFactura.ServiceReference1.CalculosLineaFacturaResponse> GesFactura.ServiceReference1.CalculosFacturaWSSoap.CalculosLineaFacturaAsync(GesFactura.ServiceReference1.CalculosLineaFacturaRequest request) {
            return base.Channel.CalculosLineaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GesFactura.ServiceReference1.CalculosLineaFacturaResponse> CalculosLineaFacturaAsync(double cantidad, double precio, double tipo_descuento, double tipo_iva) {
            GesFactura.ServiceReference1.CalculosLineaFacturaRequest inValue = new GesFactura.ServiceReference1.CalculosLineaFacturaRequest();
            inValue.Body = new GesFactura.ServiceReference1.CalculosLineaFacturaRequestBody();
            inValue.Body.cantidad = cantidad;
            inValue.Body.precio = precio;
            inValue.Body.tipo_descuento = tipo_descuento;
            inValue.Body.tipo_iva = tipo_iva;
            return ((GesFactura.ServiceReference1.CalculosFacturaWSSoap)(this)).CalculosLineaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GesFactura.ServiceReference1.HelloWorldResponse GesFactura.ServiceReference1.CalculosFacturaWSSoap.HelloWorld(GesFactura.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            GesFactura.ServiceReference1.HelloWorldRequest inValue = new GesFactura.ServiceReference1.HelloWorldRequest();
            inValue.Body = new GesFactura.ServiceReference1.HelloWorldRequestBody();
            GesFactura.ServiceReference1.HelloWorldResponse retVal = ((GesFactura.ServiceReference1.CalculosFacturaWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GesFactura.ServiceReference1.HelloWorldResponse> GesFactura.ServiceReference1.CalculosFacturaWSSoap.HelloWorldAsync(GesFactura.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<GesFactura.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            GesFactura.ServiceReference1.HelloWorldRequest inValue = new GesFactura.ServiceReference1.HelloWorldRequest();
            inValue.Body = new GesFactura.ServiceReference1.HelloWorldRequestBody();
            return ((GesFactura.ServiceReference1.CalculosFacturaWSSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
